Improved Action inputs
- Added maven-args input for configuring Maven args
- Added upload-artifact input for disabling GitHub Actions artifact
  uploading
- Improved self-tests around new inputs
- Added self-test for case with no inputs i.e. using Action defaults
  only

diff --git a/.github/workflows/self-tests.yml b/.github/workflows/self-tests.yml
--- a/.github/workflows/self-tests.yml
+++ b/.github/workflows/self-tests.yml
@@ -14,6 +14,40 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
+  no-inputs:
+    runs-on: ubuntu-latest
+    name: Passes with No Inputs (Action Defaults used)
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v7
+        with:
+          repository: telicent-oss/jena-fuseki-kafka
+
+      - name: Setup Java
+        uses: actions/setup-java@v5
+        continue-on-error: true
+        with:
+          distribution: temurin
+          java-version: 21
+          cache: maven
+
+      - name: Import GPG Key
+        uses: crazy-max/ghaction-import-gpg@v7
+        with:
+          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
+          passphrase: ${{ secrets.GPG_PASSPHRASE }}
+
+      - name: Run action
+        id: mvn-central-audit
+        uses: Telicent-io/mvn-central-audit@v1
+
+      - name: Verify Artifact Uploaded
+        id: verify-artifact
+        uses: actions/download-artifact@v8
+        with:
+          name: ${{ steps.mvn-central-audit.outputs.artifact-name }}
+          skip-decompress: true
+
   matrix:
     runs-on: ubuntu-latest
     strategy:
@@ -22,24 +56,34 @@ jobs:
         include:
           - name: Small Release passes
             repository: telicent-oss/jena-fuseki-kafka
-            success: true
             max-warnings: -1
+            upload-report: true
+            success: true
+              
+          - name: Small Release without Artifact Upload passes
+            repository: telicent-oss/jena-fuseki-kafka
+            max-warnings: -1
+            upload-report: false
+            success: true
 
           - name: Small Release with Warnings Limit fails
             repository: telicent-oss/jena-fuseki-kafka
-            success: false
             max-warnings: 0
+            upload-report: true
+            success: false
             
           - name: Large Release with Default Limits fails
             repository: telicent-oss/smart-caches-core
-            success: false
             max-warnings: -1
+            upload-report: true
+            success: false
 
           - name: Large Release with Increased Limits passes
             repository: telicent-oss/smart-caches-core
             max-files: 500
             max-size: 15000000 # 15MB
             max-warnings: -1
+            upload-report: true
             success: true
 
           - name: Large Release with Disabled Limits passes
@@ -47,16 +91,24 @@ jobs:
             max-files: -1
             max-size: -1
             max-warnings: -1
+            upload-report: true
             success: true
 
           - name: Release that requires custom Maven arguments
             repository: rvesse/airline
+            maven-args: -Prelease
             max-files: 500
+            upload-report: true
             success: true
-            extraMavenArgs: -Prelease
+
+          - name: Release that requires custom Maven arguments fails without them
+            repository: rvesse/airline
+            upload-report: true
+            success: false
 
           - name: Fails on non-Maven repository
             repository: ${{ github.repository }}
+            upload-report: true
             success: false
             
     name: ${{ matrix.name }}
@@ -84,21 +136,31 @@ jobs:
         id: mvn-central-audit
         uses: Telicent-io/mvn-central-audit@v1
         continue-on-error: true
-        env:
-          MAVEN_ARGS: ${{ matrix.extraMavenArgs }}
         with:
+          maven-args: ${{ matrix.maven-args }}
           max-files: ${{ case(matrix.max-files != '', matrix.max-files, 100) }}
           max-size: ${{ case(matrix.max-size != '', matrix.max-size, 10000000) }}
           max-warnings: ${{ matrix.max-warnings }}
           artifact-suffix: -${{ matrix.repository }}
+          upload-report: ${{ matrix.upload-report }}
 
-      - name: Verify Artifact Output
+      - name: Verify Artifact Uploaded
+        id: verify-artifact
         uses: actions/download-artifact@v8
         # Aritfact won't exist if action fails early in the audit process
         continue-on-error: true
         with:
           name: ${{ steps.mvn-central-audit.outputs.artifact-name }}
           skip-decompress: true
+
+      - name: Verify No Artifact if Upload disabled
+        if: ${{ matrix.upload-report == 'false' }}
+        shell: bash
+        run: |
+          if [ "${{ steps.verify-artifact.outcome }}" != "failure" ]; then
+            echo "::error::Artifact was uploaded despite action being configured to not upload it"
+            exit 1
+          fi
 
       - name: Verify Success
         if: ${{ matrix.success == true }}
